# Generated by Django 5.2.8 on 2025-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, choices=[('artificial_intelligence_and_robotics', 'AIR'), ('business_mathematics', ' BM'), ('digital_business_technology', 'DBT'), ('product_design_innovation', 'PDI'), ('energy_business_technology', 'EBT'), ('food_business_technology', 'FBT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=50, null=True),
        ),
    ]
